### ISSUE TITLE
Boostnote link doesn't work

### ISSUE THREAD

**Issue by lukashanak** [ReactNativeNews/React-Native-Apps#121]

**Comment by GantMan** [comment]
please submit a PR to fix

**Comment by alexakasanjeev** [comment]
Hi @lukashanak [Boost Note](https://github.com/BoostIO/boostnote-mobile), has been removed from the list because it has been archived by the maintainers and no longer maintained, and in place of that they have created new repo that uses electron & not react-native(hence removed)

new boost note project [repo](https://github.com/BoostIO/BoostNote.next)
